### ISSUE TITLE
キャンパスの画像を挿入する

### ISSUE THREAD

**Issue by saito050** [citydx2023-008/iniad-fake-homepage-team-c-#6]

**Comment by citydx2023-008** [comment]
よろしくお願いします。

**Comment by saito050** [comment]
キャンパスの画像を挿入しました。
画像ファイルは以下を参照しました。
https://www.toyo.ac.jp/nyushi/about/campus/akabanedai/gallery.html

画像サイズは全体のレイアウトに合わせて調整可です！
